### ISSUE TITLE
Getting RuntimeError - Trigger found but cannot be identified

### ISSUE THREAD

**Issue by Qarj** [Voyz/ibeam#138]
**Describe the bug**
Had a problem where I didn't get the url to link devices using Google Messages for 2FA authentication. So I switched to `voyz/ibeam:0.4.4-rc4`. This solved the 2FA problem, but now there is an authentication error and this exception is triggered.

```txt
2023-05-07 17:41:24,085|I| No active sessions, logging in...
2023-05-07 17:41:24,086|I| Loading auth webpage at https://localhost:5000/sso/Login?forwardTo=22&RL=1&ip2loc=on
2023-05-07 17:41:26,800|I| Gateway auth webpage loaded
2023-05-07 17:41:26,801|I| Login attempt number 1
2023-05-07 17:41:31,901|I| Submitting the form
2023-05-07 17:41:32,582|D| trigger: twofactbase
2023-05-07 17:41:32,582|I| Credentials correct, but Gateway requires two-factor authentication.
2023-05-07 17:41:32,583|I| Attempting to acquire 2FA code from: GoogleMessagesTwoFaHandler(driver_path=/usr/bin/chromedriver)
2023-05-07 17:41:40,075|I| First SMS found: "Your requested authentication code: 507348"
2023-05-07 17:41:40,092|I| Waiting for SMS message to be visible
2023-05-07 17:41:40,160|I| SMS message marked as read
2023-05-07 17:41:42,160|I| Cleaning up the resources. Google MSG Driver: <selenium.webdriver.chrome.webdriver.WebDriver (session="5f0d48a467be6ed65bac03707748efcc")>
2023-05-07 17:41:42,191|D| 2FA code returned: 507348
2023-05-07 17:41:42,251|I| Submitting the 2FA form
2023-05-07 17:41:45,662|E| Error encountered during authentication
Traceback (most recent call last):
  File "/srv/ibeam/src/authenticate.py", line 362, in authenticate_gateway
    trigger_identifier = identify_trigger(trigger, elements)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/ibeam/src/authenticate.py", line 160, in identify_trigger
    raise RuntimeError(f'Trigger found but cannot be identified: {trigger}')
RuntimeError: Trigger found but cannot be identified: <selenium.webdriver.remote.webelement.WebElement (session="b3d9d9d8e0f77b4f2b50a1a8f3ae7da4", element="e5e5a54b-fbf9-474c-bffa-71414b7717da")>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/ibeam/src/authenticate.py", line 409, in authenticate_gateway
    raise RuntimeError('Error encountered during authentication') from e
RuntimeError: Error encountered during authentication
2023-05-07 17:41:45,663|I| Cleaning up the resources. Display: <pyvirtualdisplay.display.Display object at 0x7f2037992890> | Driver: <selenium.webdriver.chrome.webdriver.WebDriver (session="b3d9d9d8e0f77b4f2b50a1a8f3ae7da4")>
2023-05-07 17:41:45,697|I| Authentication process failed
2023-05-07 17:41:45,702|I| Starting maintenance with interval 60 seconds
```

**Environment**
IBeam version: voyz/ibeam:0.4.4-rc4`
Docker image or standalone: Docker
Python version (standalone users only):
OS: Ubuntu 20.04

**Additional context**
I notice when I log in manually, I'm taken to an intermediate page that tries to get me to download IBKR Mobile App.

You need to Click continue to get the "Client login succeeds" message. Or if you wait a couple of minutes it will also automatically redirect to the "Client login succeeds" message on url https://localhost:5000/sso/Dispatcher

**Suggest a Fix**
I did try to study the code, but there is no line 362 in `authenticate.py`, I'm looking at the master branch - I couldn't find any other branches that are not stale, so am a bit confused.

**Comment by Voyz** [comment]
Her @Qarj thanks for reporting this issue 👍

I've just pushed out `voyz/ibeam:0.4.4-rc5` which I hope should fix this problem - I think the `IBKEY_PROMO_EL_CLASS` was not being handled properly. Let me know if that helped

**Comment by Qarj** [comment]
Thanks very much @Voyz for looking at this issue. I've installed `rc5` and I'm still getting all the errors in the log, and also `Authentication process failed`, but the weird thing is that after 60 seconds it comes good just by itself and after that it maintains the authentication just fine... I removed the container and reinstalled and the exact same thing happened.

Here is the log

```txt
2023-05-09 20:12:44,969|I| Gateway not found, starting new one...
2023-05-09 20:12:44,969|I| Note that the Gateway log below may display "Open https://localhost:5000 to login" - ignore this command.
2023-05-09 20:12:44,969|I| Starting Gateway as Linux process with params: ['bash', 'bin/run.sh', 'root/conf.yaml']
running  
 runtime path : root:dist/ibgroup.web.core.iblink.router.clientportal.gw.jar:build/lib/runtime/*
 config file  : root/conf.yaml
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/srv/clientportal.gw/build/lib/runtime/netty-common-4.1.15.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
 -> mount demo on /demo
Java Version: 11.0.18
****************************************************
version: 485dc2d762781c4ff3954ac4fb66a9469a1405f7 Mon, 20 Mar 2023 14:39:35 -0400
****************************************************
This is the Client Portal Gateway
for any issues, please contact api@ibkr.com
and include a copy of your logs
****************************************************
https://www.interactivebrokers.com/api/doc.html
****************************************************
Open https://localhost:5000 to login
App demo is available after you login under: https://localhost:5000/demo#/
2023-05-09 20:12:45,970|I| Gateway started with pid: 13
2023-05-09 20:12:45,970|D| HTTPS (unverified) request to: https://localhost:5000
2023-05-09 20:12:46,599|I| Gateway connection established
2023-05-09 20:12:46,599|D| HTTPS (unverified) request to: https://localhost:5000/v1/api/tickle
2023-05-09 20:12:46,747|I| No active sessions, logging in...
2023-05-09 20:12:46,747|I| Loading auth webpage at https://localhost:5000/sso/Login?forwardTo=22&RL=1&ip2loc=on
2023-05-09 20:12:50,106|I| Gateway auth webpage loaded
2023-05-09 20:12:50,106|I| Login attempt number 1
2023-05-09 20:12:55,214|I| Submitting the form
2023-05-09 20:12:56,444|D| trigger: twofactbase
2023-05-09 20:12:56,444|I| Credentials correct, but Gateway requires two-factor authentication.
2023-05-09 20:12:56,444|I| Attempting to acquire 2FA code from: GoogleMessagesTwoFaHandler(driver_path=/usr/bin/chromedriver)
2023-05-09 20:12:59,520|I| Web messages is not authenticated. Open this URL to pair web messages with your android phone:
2023-05-09 20:12:59,520|I| http://api.qrserver.com/v1/create-qr-code/?color=000000&bgcolor=FFFFFF&qzone=1&margin=0&size=400x400&ecc=L&data=https%3A//support.google.com/messages/%3Fp%3Dweb_computer%23%3Fc%3DCj0AqX3tUbP3Ojl6Iu0yQ5Wcp6yS2elVip0oTswQz0831ReoQa3qxaCjpjlCsEeGFoVe5sqpRyXmWa3kjH8YEiAmjRpRt5udUplN3T%2BJKWbCaA7J8cviNKQJJlqZWgtnrhogeoE3ZvJfso/ZI4D9QV7SDBJhc7RftyZXvSiE3t%2B%2BQ9A%3D
2023-05-09 20:13:24,067|I| First SMS found: "Your requested authentication code: 563219"
2023-05-09 20:13:24,081|I| Waiting for SMS message to be visible
2023-05-09 20:13:24,146|I| SMS message marked as read
2023-05-09 20:13:26,147|I| Cleaning up the resources. Google MSG Driver: <selenium.webdriver.chrome.webdriver.WebDriver (session="0338157e13f09045cc9f1fe6ac2299c8")>
2023-05-09 20:13:26,173|D| 2FA code returned: 563219
2023-05-09 20:13:26,237|I| Submitting the 2FA form
2023-05-09 20:13:29,975|I| Handling IB-Key promo display...
2023-05-09 20:13:30,447|E| Error encountered during authentication
Traceback (most recent call last):
  File "/srv/ibeam/src/authenticate.py", line 373, in authenticate_gateway
    trigger_identifier = identify_trigger(trigger, elements)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/ibeam/src/authenticate.py", line 145, in identify_trigger
    if trigger.get_attribute('id') == elements['TWO_FA_EL_ID']:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 139, in get_attribute
    attributeValue = self.parent.execute_script(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 634, in execute_script
    return self.execute(command, {
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=90.0.4430.212)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/ibeam/src/authenticate.py", line 412, in authenticate_gateway
    raise RuntimeError('Error encountered during authentication') from e
RuntimeError: Error encountered during authentication
2023-05-09 20:13:30,450|I| Cleaning up the resources. Display: <pyvirtualdisplay.display.Display object at 0x7fa9ea489190> | Driver: <selenium.webdriver.chrome.webdriver.WebDriver (session="8227ce798e3b97e355a9ca125076f5b1")>
2023-05-09 20:13:30,492|I| Authentication process failed
2023-05-09 20:13:30,498|I| Starting maintenance with interval 60 seconds
2023-05-09 20:14:30,498|I| Maintenance
2023-05-09 20:14:30,499|D| HTTPS (unverified) request to: https://localhost:5000/v1/api/tickle
2023-05-09 20:14:30,576|I| Gateway running and authenticated
2023-05-09 20:15:30,499|I| Maintenance
2023-05-09 20:15:30,499|D| HTTPS (unverified) request to: https://localhost:5000/v1/api/tickle
2023-05-09 20:15:30,590|I| Gateway running and authenticated
2023-05-09 20:16:30,498|I| Maintenance
2023-05-09 20:16:30,499|D| HTTPS (unverified) request to: https://localhost:5000/v1/api/tickle
2023-05-09 20:16:30,576|I| Gateway running and authenticated
```

It is a bit of a strange one, but at least I end up authenticated, thanks!

We might be able to avoid the stale element problem by waiting a few seconds between each step in the 2FA process to give the page time to settle.

**Comment by Voyz** [comment]
Gotcha, you helped me identify another bug - `trigger` var wasn't reassigned after recognising `IBKEY_PROMO_EL_CLASS`. Just pushed `voyz/ibeam:0.4.4-rc6` could you give it a shot?

The authentication failed and then seeming successful makes sense to me - the login works, but our handling of the success state wasn't right.

**Comment by Qarj** [comment]
Thanks very much for putting that together! Sorry about the delay in getting back to you. The log is now looking a lot cleaner on startup:

```txt
Open https://localhost:5000 to login
App demo is available after you login under: https://localhost:5000/demo#/
2023-05-15 19:57:27,387|I| Gateway started with pid: 13
2023-05-15 19:57:27,387|D| HTTPS (unverified) request to: https://localhost:5000
2023-05-15 19:57:28,018|I| Gateway connection established
2023-05-15 19:57:28,018|D| HTTPS (unverified) request to: https://localhost:5000/v1/api/tickle
2023-05-15 19:57:28,112|I| No active sessions, logging in...
2023-05-15 19:57:28,112|I| Loading auth webpage at https://localhost:5000/sso/Login?forwardTo=22&RL=1&ip2loc=on
2023-05-15 19:57:31,684|I| Gateway auth webpage loaded
2023-05-15 19:57:31,684|I| Login attempt number 1
2023-05-15 19:57:36,792|I| Submitting the form
2023-05-15 19:57:37,471|D| trigger: twofactbase
2023-05-15 19:57:37,471|I| Credentials correct, but Gateway requires two-factor authentication.
2023-05-15 19:57:37,471|I| Attempting to acquire 2FA code from: GoogleMessagesTwoFaHandler(driver_path=/usr/bin/chromedriver)
2023-05-15 19:57:40,170|I| Web messages is not authenticated. Open this URL to pair web messages with your android phone:
2023-05-15 19:57:40,170|I| http://api.qrserver.com/v1/create-qr-code/ ...
2023-05-15 19:58:05,797|I| First SMS found: "Your requested authentication code: 434572"
2023-05-15 19:58:05,804|I| Waiting for SMS message to be visible
2023-05-15 19:58:05,884|I| SMS message marked as read
2023-05-15 19:58:07,884|I| Cleaning up the resources. Google MSG Driver: <selenium.webdriver.chrome.webdriver.WebDriver (session="114fe009378e06070106fa057e0afe94")>
2023-05-15 19:58:07,923|D| 2FA code returned: 434572
2023-05-15 19:58:07,984|I| Submitting the 2FA form
2023-05-15 19:58:11,440|I| Handling IB-Key promo display...
2023-05-15 19:58:11,899|I| Webpage displayed "Client login succeeds"
2023-05-15 19:58:13,900|I| Cleaning up the resources. Display: <pyvirtualdisplay.display.Display object at 0x7fa69d8d7c90> | Driver: <selenium.webdriver.chrome.webdriver.WebDriver (session="733d3beb48ab58820511ae3b7b461c32")>
2023-05-15 19:58:13,943|I| Authentication process succeeded
2023-05-15 19:58:16,943|D| HTTPS (unverified) request to: https://localhost:5000/v1/api/tickle
2023-05-15 19:58:17,206|I| Gateway running and authenticated.
2023-05-15 19:58:17,211|I| Starting maintenance with interval 60 seconds
2023-05-15 19:59:17,211|I| Maintenance
2023-05-15 19:59:17,212|D| HTTPS (unverified) request to: https://localhost:5000/v1/api/tickle
2023-05-15 19:59:17,263|I| Gateway running and authenticated
```

**Comment by Voyz** [comment]
Superb @Qarj thanks for reporting back. Glad to hear the problem seems to be fixed 👍

**Comment by Voyz** [comment]
Closing as this is addressed with https://github.com/Voyz/ibeam/releases/tag/v0.4.4. Thanks for the contribution 😊
