### ISSUE TITLE
[not an issue with ibeam] Account seems to be limited after a few days of running ('Gateway session active but not authenticated')

### ISSUE THREAD

**Issue by beanhedge** [Voyz/ibeam#19]
First of all, thank you so much for this project, it's been a great help.

I just wanted to report that my account seems to have been limited after running the container 24/7 over 4 days.  (This isn't a problem with ibeam because manually running the client has the same issue.  I just wanted to put it here to warn others.)

It's been running fine the past few days with:
```
2021-04-23 04:40:46,760|I| Gateway session found but not authenticated, authenticating...
2021-04-23 04:40:52,701|I| Login succeeded
2021-04-23 04:40:53,809|E| Gateway session active but not authenticated
2021-04-23 04:41:46,761|I| Gateway running and authenticated
2021-04-23 04:42:46,777|I| Gateway running and authenticated
2021-04-23 04:43:46,766|I| Gateway running and authenticated
2021-04-23 04:44:46,764|I| Gateway running and authenticated

```

but today it started doing

```
2021-04-25 18:16:55,886|E| Gateway session active but not authenticated
2021-04-25 18:17:46,775|I| Gateway session found but not authenticated, authenticating...
2021-04-25 18:17:53,064|I| Login succeeded
2021-04-25 18:17:54,168|E| Gateway session active but not authenticated
2021-04-25 18:18:46,784|I| Gateway session found but not authenticated, authenticating...
2021-04-25 18:18:53,107|I| Login succeeded
2021-04-25 18:18:54,212|E| Gateway session active but not authenticated
2021-04-25 18:19:46,765|I| Gateway session found but not authenticated, authenticating...
2021-04-25 18:19:52,941|I| Login succeeded
2021-04-25 18:19:54,047|E| Gateway session active but not authenticated
2021-04-25 18:20:46,804|I| Gateway session found but not authenticated, authenticating...
2021-04-25 18:20:53,058|I| Login succeeded
```

I started the portal manually on my computer to check what was going on.  Login through the web page still works, I still get "Client login succeeds".  https://localhost:5000/v1/portal/sso/validate and https://localhost:5000/v1/portal/tickle, https://localhost:5000/v1/portal/portfolio/accounts still return 200.  However,  ticker shows "authenticated: false".
https://localhost:5000/v1/portal/iserver/marketdata/history and https://localhost:5000/v1/portal/iserver/accounts
gives 
```
401
{"error":"not authenticated","statusCode":401}
```

**Comment by Voyz** [comment]
Hey @beanhedge welcome to IBeam! 😊

Thanks for reporting your issues. Unfortunately, like you correctly observe this doesn't seem to be IBeam failing but Gateway (or IBKR server) that's not handling authentication well. IBeam checks for that 'authenticated' flag and attempts to reauthenticate each time it sees it set to False. 

To highlight the importance of these issues and possibly accelerate improvements, I'd suggest you submit a ticket with IBKR support highlighting this problem.

If you have any further information on why this issue seems to be appearing - for instance some repeated pattern - let us know. Otherwise the current advice is to just wait it through - it oftentimes resolves itself after some time.

Let me know if I could help you in any way here 👍
Thanks! 👋 Voy

**Comment by beanhedge** [comment]
The account issue resolved itself after a couple days.  They did email me back and told me to try:

```
1. Please open conf.yaml under the root folder.
2. Change the proxyRemoteHost to “https://1.api.ibkr.com”
```
I didn't try it because my issue was already resolved.

However, today I hit a new issue with the fetch endpoint: 
`{'error': 'Too many active charts. Cannot create a new one. Please unsubscribe from old subscriptions to allow new ones. ', 'statusCode': 200}`

I ran a get request against "https://localhost:5000/v1/api/iserver/marketdata/unsubscribeall" and got {'unsubscribed': True} but it didn't help.  I emailed them again and will post what they say.

**Comment by Voyz** [comment]
That's useful, I'll see if using that different proxy URL helps at all - thanks a lot for posting this update.

That new error you're running into sounds more like what the error itself says. Maybe try through TWS?

**Comment by beanhedge** [comment]
I heard back from them today, I got:

**Comment by Greatsamps** [comment]
We have just started to play with this project, and are getting the above error straight off the bat. We are NOT getting the error however when running the windows gateway locally.

Just to be clear, the docker container has never been able to successfully establish authentication it would seem.

2021-07-18 07:41:18,948|I| Gateway started with pid: 13
2021-07-18 07:41:25,847|I| No active sessions, logging in...
2021-07-18 07:41:43,845|I| Authentication process succeeded
2021-07-18 07:41:46,899|E| Gateway session active but not authenticated
2021-07-18 07:41:47,397|I| ############ Starting IBeam version 0.3.0 ############
2021-07-18 07:41:47,442|I| Starting maintenance with interval 60 seconds
2021-07-18 07:42:52,596|I| Gateway session found but not authenticated, authenticating...
2021-07-18 07:43:03,647|I| Authentication process succeeded
2021-07-18 07:43:06,705|E| Gateway session active but not authenticated
2021-07-18 07:43:52,988|I| No active sessions, logging in...
2021-07-18 07:44:05,079|I| Authentication process succeeded
2021-07-18 07:44:08,133|E| Gateway session active but not authenticated
2021-07-18 07:44:52,998|I| No active sessions, logging in...
2021-07-18 07:45:04,500|I| Authentication process succeeded
2021-07-18 07:45:07,675|E| Gateway session active but not authenticated
2021-07-18 07:45:52,588|I| Gateway session found but not authenticated, authenticating...

**Comment by Voyz** [comment]
Hey @Greatsamps thanks for your contribution. It's interesting to hear that you notice the Gateway working correctly when initialised without IBeam. Could I ask you to run IBeam with LOG_LEVEL set to debug and pass over the program output produced?

**Comment by Greatsamps** [comment]
Like this:

-e LOG_LEVEL=debug

Made no difference to output..

**Comment by Voyz** [comment]
Sorry for the confusion, running it in debug requires you to specify it as a variable used by the Python 'logging' module, therefore you need to put DEBUG in all caps. See here for more:

https://github.com/Voyz/ibeam/wiki/IBeam-Configuration#debugging

**Comment by Greatsamps** [comment]
Ok got it working, it's IBEAM_LOG_LEVEL that needed to be set.

incase this matters, this is a paper trading account.

output below:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/srv/clientportal.gw/build/lib/runtime/netty-common-4.1.15.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
 -> mount demo on /demo
Java Version: 11.0.9.1
****************************************************
version: ed4af2592e9dd4a784d5403843bd18292fd441ea Fri, 9 Nov 2018 13:23:18 -0500
****************************************************
This is a Beta release of the Client Portal Gateway
for any issues, please contact api@ibkr.com
and include a copy of your logs
****************************************************
https://www.interactivebrokers.com/api/doc.html
****************************************************
Open https://localhost:5000 to login
App demo is available after you login under: https://localhost:5000/demo/
2021-07-18 16:34:44,828|I| Gateway started with pid: 12
2021-07-18 16:34:44,828|D| HTTPS (unverified) request to: https://localhost:5000
2021-07-18 16:34:44,832|D| Cannot ping Gateway. Retrying for another 20 seconds
2021-07-18 16:34:45,833|D| HTTPS (unverified) request to: https://localhost:5000
2021-07-18 16:34:51,702|D| Gateway connection established
2021-07-18 16:34:51,702|D| HTTPS (unverified) request to: https://localhost:5000/v1/api/tickle
2021-07-18 16:34:51,822|I| No active sessions, logging in...
2021-07-18 16:34:51,823|D| Loading auth webpage at https://localhost:5000/sso/Login?forwardTo=22&RL=1&ip2loc=on
2021-07-18 16:34:59,350|D| Gateway auth webpage loaded
2021-07-18 16:34:59,350|D| Login attempt number 1
2021-07-18 16:35:04,509|D| Submitting the form
2021-07-18 16:35:06,416|D| Webpage displayed "Client login succeeds"
2021-07-18 16:35:08,418|D| Cleaning up the resources. Display: <pyvirtualdisplay.display.Display object at 0x7fb70e5e99d0> | Driver: <selenium.webdriver.chrome.webdriver.WebDriver (session="334adb27932b8065518ee13664eabb0e")>
2021-07-18 16:35:08,472|I| Authentication process succeeded
2021-07-18 16:35:11,475|D| HTTPS (unverified) request to: https://localhost:5000/v1/api/tickle
2021-07-18 16:35:11,525|E| Gateway session active but not authenticated
2021-07-18 16:35:12,027|I| ############ Starting IBeam version 0.3.0 ############
2021-07-18 16:35:12,031|D| {'INPUTS_DIR': '/srv/inputs/', 'OUTPUTS_DIR': '/srv/outputs', 'GATEWAY_DIR': '/srv/clientportal.gw', 'CHROME_DRIVER_PATH': '/srv/chrome_driver/chromedriver', 'GATEWAY_STARTUP': 20, 'GATEWAY_PROCESS_MATCH': 'ibgroup.web.core.clientportal.gw.GatewayStart', 'MAINTENANCE_INTERVAL': 60, 'SPAWN_NEW_PROCESSES': False, 'LOG_LEVEL': 'DEBUG', 'LOG_TO_FILE': True, 'REQUEST_RETRIES': 1, 'REQUEST_TIMEOUT': 15, 'GATEWAY_BASE_URL': 'https://localhost:5000', 'ROUTE_AUTH': '/sso/Login?forwardTo=22&RL=1&ip2loc=on', 'ROUTE_USER': '/v1/api/one/user', 'ROUTE_VALIDATE': '/v1/portal/sso/validate', 'ROUTE_REAUTHENTICATE': '/v1/portal/iserver/reauthenticate?force=true', 'ROUTE_AUTH_STATUS': '/v1/api/iserver/auth/status', 'ROUTE_TICKLE': '/v1/api/tickle', 'USER_NAME_EL_ID': 'user_name', 'PASSWORD_EL_ID': 'password', 'SUBMIT_EL_ID': 'submitForm', 'ERROR_EL_ID': 'ERRORMSG', 'SUCCESS_EL_TEXT': 'Client login succeeds', 'OAUTH_TIMEOUT': 15, 'PAGE_LOAD_TIMEOUT': 15, 'ERROR_SCREENSHOTS': False, 'MAX_FAILED_AUTH': 5, 'MAX_IMMEDIATE_ATTEMPTS': 10, 'TWO_FA_EL_ID': 'twofactbase', 'TWO_FA_INPUT_EL_ID': 'chlginput', 'TWO_FA_HANDLER': None, 'STRICT_TWO_FA_CODE': True}
2021-07-18 16:35:12,078|I| Starting maintenance with interval 60 seconds
2021-07-18 16:36:12,078|D| Maintenance
2021-07-18 16:36:12,080|D| HTTPS (unverified) request to: https://localhost:5000/v1/api/tickle
2021-07-18 16:36:17,238|I| Gateway session found but not authenticated, authenticating...
2021-07-18 16:36:17,239|D| Loading auth webpage at https://localhost:5000/sso/Login?forwardTo=22&RL=1&ip2loc=on
2021-07-18 16:36:19,792|D| Gateway auth webpage loaded
2021-07-18 16:36:19,792|D| Login attempt number 1
2021-07-18 16:36:24,945|D| Submitting the form
2021-07-18 16:36:26,181|D| Webpage displayed "Client login succeeds"
2021-07-18 16:36:28,183|D| Cleaning up the resources. Display: <pyvirtualdisplay.display.Display object at 0x7f0260867e50> | Driver: <selenium.webdriver.chrome.webdriver.WebDriver (session="582f791a294bde309c74704ba93d04de")>
2021-07-18 16:36:28,236|I| Authentication process succeeded
2021-07-18 16:36:31,240|D| HTTPS (unverified) request to: https://localhost:5000/v1/api/tickle
2021-07-18 16:36:31,292|E| Gateway session active but not authenticated

**Comment by Voyz** [comment]
Great, thanks for posting this. Everything seems to be in order, which would point at a similar issue that @beanhedge encountered. It's interesting that you say that running the Gateway manually doesn't cause this issue. 

In order to verify if that indeed is the case, could I ask you to do the following in short succession:

1. Start IBeam and note if this issue persist, then stop IBeam.
2. Start the Gateway manually without IBeam
3. Performing a tickle request on it once it's running and write down the response of the tickle request.
4. Stop the Gateway that's running manually
5. Start IBeam once again and see if the issue continues to persist.

Thank you!

**Comment by Greatsamps** [comment]
Hi,

Sorry for delay on this. Here is output from step 3:

{"session":"b42059b2586ea798f8219b8ca26aa332","ssoExpires":594650,"collission":false,"userId":65305922,"iserver":{"tickle":true,"authStatus":{"authenticated":false,"competing":false,"connected":true,"message":"","MAC":"08:F1:EA:83:2D:DC"}}}

It appears you are using the beta version of the GW whereas i am using the stable one. Could this be the difference?

**Comment by Greatsamps** [comment]
I have found something else strange. It seems running the GW locally i can't access any of the iserver endpoints. When i call iserver/auth/status i get the following:

{
    "authenticated": false,
    "competing": false,
    "connected": true,
    "message": "",
    "MAC": "08:F1:EA:83:2D:DC",
    "fail": "xxx can't authenticate"
}

This is a paper trading account, do you think that could be the problem, and perhaps this is also why IBeam is complaining?

**Comment by Voyz** [comment]
Thanks for doing this test and for passing over the results 👍

I don't think the paper account should have any influence on it, as I've noticed this error appearing on both paper and live accounts. We tried upgrading to beta version at some point but it didn't seem to solve the issues at hand so we reverted back to the stable from 9 Nov 2018 which I believe is the latest. That looks to me like the same issue as before - there's something failing at IBKR side, and even your vanilla Gateway fails to authenticate.

I'd recommend you get in touch with the IBKR support and try to work with them to figure out why the authentication fails despite providing correct credentials. I'm sorry I cannot be of more help, but this is a known problem that we cannot jump over on IBeam side despite multiple attempts. Feel free to suggest any fixes if you can think of any.

**Comment by kavindu-athaudha** [comment]
Hi Voyz,

Need to start this out by thanking you for the hard work you've done; you've really done a huge addition to everyone trying to use IBKR's REST API.

I faced this issue as well and I just contacted IBKR support. What they said is that it's a known issue and that they're working on it. But by the looks of this thread, this has been going on for months but to no avail.

IBKR support requested me to try the beta version, but this thread has shown me that that won't work as well.
It doesn't seem like Interactive Brokers is taking priority on this significant issue.

Is there any suggestion we, as a community, can do to pressure Interactive Brokers to fixing this?

**Comment by Voyz** [comment]
hey @kavindu-athaudha welcome and thanks for your super kind words! 😊

Thanks for sharing your story about the conversation with IBKR. Indeed, we're around 7 months into these issues appearing regularly and there doesn't seem to be much improvement. I've tested the beta and stable versions and both appear to have this issue. From what I've read, IBKR never seemed to put retail investors and small firms, who probably will be primary users of the Web API, high up on their priority list - somewhat understandably.

> Is there any suggestion we, as a community, can do to pressure Interactive Brokers to fixing this?

And to answer your question - I honestly have no idea. I wouldn't want to act aggressively towards them (eg. on social media), and I don't know what methods there are to tackle behemoth companies into focusing on their underserved audience. If you (or anyone reading this) would have suggestions then please share them here.

**Comment by kavindu-athaudha** [comment]
> I wouldn't want to act aggressively towards them (eg. on social media)

Yes, I agree on not doing anything aggressive.
My assumption is that they have not prioritized this issue as they probably receive few tickets from support regarding this issue (despite a lot of people facing the issue, not everyone raises tickets with them).

What I was thinking was something along the lines of getting more people (e.g. like the people in this thread) to all raise the issue with Interactive Brokers so they have a clearer picture of how important this issue is and maybe they would prioritize it more.

**Comment by Voyz** [comment]
Okay cool, @kavindu-athaudha and how would you suggest we could organise in such way? I advice all IBeam users to contact IBKR support when running into this issue, do you have any other ideas for how we could encourage them to submit a ticket?

**Comment by usr97629238** [comment]
It looks that the gateway is subject to some obscure rate limits. Also it looks like that sending malformed requests also provokes de-authentication.
And I'm afraid that submitting tickets would end with the usual boilerplate replies.
So I'd say a better approach would be approaching them nicely (they have an account here https://github.com/InteractiveBrokers) and asking for indepth infos on those rate limits, etc.

**Comment by gmara13** [comment]
Been having these active but unauthenticated error cycles pretty frequently. latest one was lasting for the the past 10 hours. i switch proxy as below:
```
1. Please open conf.yaml under the root folder.
2. Change the proxyRemoteHost to “https://1.api.ibkr.com”
```
and it immediately worked when reloading the container...FYI

**Comment by Voyz** [comment]
hey @gmara13 thanks for following up on this - can I ask you if you're doing this every time the error appears, or do you mean that switching to it just once solves the issue for you forever?

**Comment by buntagonalprism** [comment]
Been getting the same issue of being able to login but repeatedly not being authenticated for trading. It seems to start happening after a few days of running IBeam continuously. I've found that calling the `/logout` endpoint manually with Postman seems to fix it a few minutes later. For example after 19 hours of continuous reauthentication, I sent a request to logout at `01:47:57` and authentication was succeeding a minute and a half later. 

```
2021-10-04 01:43:45,370|E| Gateway session active but not authenticated
2021-10-04 01:44:28,579|I| Gateway session found but not authenticated, authenticating...
2021-10-04 01:44:39,165|I| Authentication process succeeded
2021-10-04 01:44:42,528|E| Gateway session active but not authenticated
2021-10-04 01:45:28,589|I| Gateway session found but not authenticated, authenticating...
2021-10-04 01:45:39,165|I| Authentication process succeeded
2021-10-04 01:45:42,523|E| Gateway session active but not authenticated
2021-10-04 01:46:28,435|I| Gateway session found but not authenticated, authenticating...
2021-10-04 01:46:39,106|I| Authentication process succeeded
2021-10-04 01:46:42,468|E| Gateway session active but not authenticated
2021-10-04 01:47:28,429|I| Gateway session found but not authenticated, authenticating...
2021-10-04 01:47:39,365|I| Authentication process succeeded
2021-10-04 01:47:42,867|E| Gateway session active but not authenticated
2021-10-04 01:48:28,451|I| Gateway session found but not authenticated, authenticating...
2021-10-04 01:48:39,850|I| Authentication process succeeded
2021-10-04 01:48:43,196|E| Gateway session active but not authenticated
2021-10-04 01:49:28,426|I| Gateway running and authenticated
2021-10-04 01:50:28,448|I| Gateway running and authenticated
2021-10-04 01:51:28,429|I| Gateway running and authenticated
2021-10-04 01:52:28,437|I| Gateway running and authenticated
2021-10-04 01:53:28,431|I| Gateway running and authenticated
```

**Comment by Voyz** [comment]
Thanks for sharing this info @buntagonalprism - there's been another suggestion that `/logout` seems to help in this case - https://github.com/Voyz/ibeam/issues/7#issuecomment-932438473 I'll look into it 👍

**Comment by danielkrizian** [comment]
> Been having these active but unauthenticated error cycles pretty frequently. latest one was lasting for the the past 10 hours. i switch proxy as below:
> 
> ```
> 1. Please open conf.yaml under the root folder.
> 2. Change the proxyRemoteHost to “https://1.api.ibkr.com”
> ```
> 
> and it immediately worked when reloading the container...FYI

this approach resolved the issue for me, which according to IBKR support lies in their load balancer at api.ibkr.com. 

if `/iserver/reauthenticate` when `proxyRemoteHost https://api.ibkr.com` or `proxyRemoteHost https://1.api.ibkr.com` doesn't change the `authenticated` status to `true` (see the fields in `/tickle` endpoint ), change `proxyRemoteHost` to any of the **1-8** nodes where the IBKR balances the load. 
i tried `proxyRemoteHost https://1.api.ibkr.com` and `proxyRemoteHost https://8.api.ibkr.com` - didn't work either, ultimately `proxyRemoteHost https://7.api.ibkr.com` helped.

probably capacity issue of each node that IBKR haven't addressed yet?

@Voyz perhaps IBEAM can make trial-error on nodes 1-8 until it finds the one that has spare capacity - until IBKR fixes their load balancer.

**Comment by Voyz** [comment]
Hi @danielkrizian yes that indeed seems to be a problem with the load balancer on IBKR side and they do suggest shuffling these numbers between 1-8 to look for an available one. The solution you propose is something we're already considering (https://github.com/Voyz/ibeam/issues/7#issuecomment-930196898) however first I'd like to see if simply logging out and restarting the gateway would help, as shuffling these numbers would require IBeam to write into the `conf.yaml` which comes with risks of its own. Thanks for suggesting this fix in either case, appreciate your contribution to the discussion 👍

**Comment by danielkrizian** [comment]
> first I'd like to see if simply logging out and restarting the gateway would help

hi @Voyz i've tried that before, albeit on the API level - calling `/logout` endpoint before any combination of `/iserver/reauthenticate`, `/tickle`, `/sso/validate` and `/iserver/auth/status` did not change the iserver's `authenticated` status from `false` to `true`. only switching the `proxyRemoteHost` config to a different (less busy?) node - admittedly after the gateway restart, so that the new `proxyRemoteHost` is picked up.

i think the IBKR java gateway app under the wraps implements the calls to 
1. `/iserver/auth/ssodh/init` , 
2. `/iserver/auth/ssodh/response` and 
3. the calculation of response hash:
```
export function compute_sk(seed, verifier) {
     const hash = crypto.createHash(‘sha1’);
     hash.update(Buffer.from(seed + verifier, ‘hex’));
     return hash.digest(‘hex’);
}
```
as described in https://www.tradersinsight.news/ibkr-quant-news/tutorial-web-api-connect-to-brokerage-session/

*if* the gateway restart is needed to reset some local cache, the need for full-blown restart could be prevented programmatically by implementing the abovementioned three responsibilities, taking the load-balancer node as an input dynamically.

**Comment by Voyz** [comment]
> only switching the proxyRemoteHost config to a different (less busy?) node

Thanks for reporting on these attempts, it's useful to know 👏 Seeing that `/logout` seemed to work for some users, I've just released a new release candidate `docker pull voyz/ibeam:0.4.0-rc1` with that functionality in place. Give it a shot when you find some time, and should it prove unsuccessful I'll look into proxy wrangling in the conf.yaml.

> if the gateway restart is needed to reset some local cache, the need for full-blown restart could be prevented programmatically by implementing the abovementioned three responsibilities, taking the load-balancer node as an input dynamically.

Thanks for suggesting this, but I'm not sure I'm following your proposal here - sorry. Do I understand you suggest to call `/iserver/auth/ssodh/init`, calculate the hash using the logic you pasted and send it to `/iserver/auth/ssodh/response`? If I understand correctly we'd be reproducing what the Gateway is currently doing, how would this help solve the `Gateway session active but not authenticated`? Did you try this method?

**Comment by danielkrizian** [comment]
> suggest to call `/iserver/auth/ssodh/init`, calculate the hash using the logic you pasted and send it to `/iserver/auth/ssodh/response`? If I understand correctly we'd be reproducing what the Gateway is currently doing

my understanding too. however, gateway java app from IBKR might also be doing *more* than that, like caching some hashes that are time-dependent and keeping sending the same hash (until gateway restart and cache reset) to the load balancer, which in turn can cache it too server-side to identify client gateway sessions.

the above is just a conjecture, but explains my observations when sometimes not even changing nodes (described above) and `/logout` calls help until the whole gateway (cache/sessionid?) was restarted.

> how would this help solve the `Gateway session active but not authenticated`
having own gateway app that implements the three functions above and accepts load balancer node number as a (dynamic) parameter in a function (instead of reading it from static config file) would be a more lightweight method of resetting the session cache than the full-blown gateway app restart.

**Comment by buntagonalprism** [comment]
> > only switching the proxyRemoteHost config to a different (less busy?) node
> 
> Thanks for reporting on these attempts, it's useful to know 👏 Seeing that `/logout` seemed to work for some users, I've just released a new release candidate `docker pull voyz/ibeam:0.4.0-rc1` with that functionality in place. Give it a shot when you find some time, and should it prove unsuccessful I'll look into proxy wrangling in the conf.yaml.
> 
> > if the gateway restart is needed to reset some local cache, the need for full-blown restart could be prevented programmatically by implementing the abovementioned three responsibilities, taking the load-balancer node as an input dynamically.
> 
> Thanks for suggesting this, but I'm not sure I'm following your proposal here - sorry. Do I understand you suggest to call `/iserver/auth/ssodh/init`, calculate the hash using the logic you pasted and send it to `/iserver/auth/ssodh/response`? If I understand correctly we'd be reproducing what the Gateway is currently doing, how would this help solve the `Gateway session active but not authenticated`? Did you try this method?

Thanks for the rapid update! Will try out the new `0.4.0-rc1` version. 

With the current version I've just observed calling `/logout` manually did not resolve the issue after 12 minutes. But calling logout a second time then resolved issue within a minute. So hopefully a few repeated logouts will work.

**Comment by isque03** [comment]
Thanks for setting up this project @Voyz ! Great work.

I've been working with the IBKR api and I see the same issue where, after a while, sso is authenticated, but the brokerage session will not authenticate for several hours. Reauthenticating through the https://localhost:5000/ page does not fix the issue.

Short summary of what worked:

I tried the suggestions from the comment above and so far it has been successful.

1. Gateway gets in bad state where you can't get an authenticated brokerage session
2. Trigger /logout endpoint
3. Next, trigger /reauthenticate
4. Back in action again!

I did *not* change the proxyRemoteHost to N.api.ibkr.com. Just left it at the default.

More details below:
From the gateway logs you can it it attempting the ssodh flow as described here: https://www.tradersinsight.news/ibkr-quant-news/tutorial-web-api-connect-to-brokerage-session/

Note the requests with 200 response code (,200) resulted in successful brokerage session authentication.
After a while those, that POST starts getting a 503 response. This is where the gateway fails to authenticate. 

> -> request: /v1/api/iserver/auth/ssodh/init
> -> POST https://api.ibkr.com/v1/api/iserver/auth/ssodh/init,200|541ms
> -> request: /v1/api/iserver/auth/ssodh/init
> -> POST https://api.ibkr.com/v1/api/iserver/auth/ssodh/init,200|30ms
> -> request: /v1/api/iserver/auth/ssodh/init
> -> POST https://api.ibkr.com/v1/api/iserver/auth/ssodh/init,503|10041ms
> -> request: /v1/api/iserver/auth/ssodh/init
> -> POST https://api.ibkr.com/v1/api/iserver/auth/ssodh/init,503|10047ms

I then did a POST to the gateway using https://localhost:5000/v1/portal/iserver/reauthenticate

You can see the gateway attempts the ssodh authentication flow, in response to this post, but it's continuing to fail due to the 503 response from api.ibkr.com

> 15:42:00.388 INFO  vert.x-eventloop-thread-0 BaseServiceProxy     : -> POST https://api.ibkr.com/v1/api/iserver/auth/ssodh/init,503|10102ms
> 15:42:00.389 WARN  vert.x-eventloop-thread-0 BaseServiceProxy     : failed /v1/api/iserver/auth/ssodh/init | reason 503
> 15:42:00.389 DEBUG vert.x-eventloop-thread-0 ClientPortalService  : iserver init : null
> 15:42:00.389 ERROR vert.x-eventloop-thread-0 ClientPortalService  : iserver init failed
> io.vertx.core.impl.NoStackTraceThrowable: 503
> 15:42:00.390 DEBUG vert.x-eventloop-thread-0 BaseServiceProxy     : forward event ON_SSODH_FAILED, payload none
> 15:42:00.390 ERROR vert.x-eventloop-thread-0 GatewayHttpProxy     : ssodh failed, retry with /iserver/reauthenticate
> 15:42:10.090 INFO  vert.x-eventloop-thread-0 BaseServiceProxy     : -> POST https://api.ibkr.com/v1/api/iserver/auth/ssodh/init,503|10095ms
> 15:42:10.090 WARN  vert.x-eventloop-thread-0 BaseServiceProxy     : failed /v1/api/iserver/auth/ssodh/init | reason 503
> 15:42:10.090 DEBUG vert.x-eventloop-thread-0 ClientPortalService  : iserver init : null
> 15:42:10.091 ERROR vert.x-eventloop-thread-0 ClientPortalService  : iserver init failed
> io.vertx.core.impl.NoStackTraceThrowable: 503
> 15:42:10.092 DEBUG vert.x-eventloop-thread-0 BaseServiceProxy     : forward event ON_SSODH_FAILED, payload none
> 15:42:10.092 ERROR vert.x-eventloop-thread-0 GatewayHttpProxy     : ssodh failed, retry with /iserver/reauthenticate

Given the thread above I next did a logout when it was in this state of continuous 503 errors.

`curl -X POST https://localhost:5000/v1/portal/logout -H 'Content-Type: application/json' -d {}`

After that I did a reauthenticate:

`curl -X POST https://localhost:5000/v1/portal/iserver/reauthenticate`

I can see in the gateway logs it then completes an SSO reauthentication, then also attempts the brokerage session reauthentication with the ssodh endpoints.

This time, ssodh/init returns a 200 response again, and the gateway is able to setup a new brokerage session.

`-> POST https://api.ibkr.com/v1/api/iserver/auth/ssodh/init,200|169ms`

 I'm not sure if this is a 100% reliable workaround since I've not tried it that many times, but at least there was some success.

**Comment by Voyz** [comment]
@danielkrizian thanks for outlining your idea in more detail - that's very helpful and I understand it now 👍 At the moment I won't have time to investigate this idea further, but if you're successful in putting together some code that does such reauthentication then we could look at adding it into IBeam

**Comment by Voyz** [comment]
@isque03 thanks for bringing up your observations and outlining them in so much detail. Just to double check - which IBeam image are you using? I guess that adding a call to `/reauthenticate` between logging out and restarting won't add a lot of overhead so we could just try putting it in and see if it helps - what do you recon?

**Comment by Voyz** [comment]
Hey @andrey-ned thanks for the kind words and for using IBeam 😊 The issue you're encountering is the same as one everyone else is experiencing here. We're waiting for IBKR to solve it on their end, while some work is being done to mitigate its impact. You can read about it in this very issue, however there isn't any direct fix I can suggest right now. Stay in tune for more updates in the future 👍

**Comment by andrey-ned** [comment]
Hi, @Voyz, so It's official problem on IBRK side ?

**Comment by Voyz** [comment]
@andrey-ned We don't know how official it is, but it is almost certainly a problem with Gateway and IBKR servers.

**Comment by Voyz** [comment]
`voyz/ibeam:0.4.0-rc3` was just released with the alternative reauthentication logic as proposed here: https://github.com/Voyz/ibeam/issues/40#issuecomment-995617649

Let us know how the 0.4.0 versions are working for you - has it helped with the repeated `Gateway session active but not authenticated`?

**Comment by jeffj0110** [comment]
Not using ibeam (need to check it out).  I ran into this issue after using the REST client portal API with the local gateway running in my Windows desktop.

I changed proxyRemoteHost:  to "https://1.api.ibkr.com" and it did resolve the lost authentication issue for me.

Thanks everyone for your comments.

**Comment by Voyz** [comment]
To anyone involved - seeing I haven't heard back regarding this issue I'm going to be looking at merging the `v0.4.0` into the `master` and releasing it as `latest`. Let me know if you'd want to bring something up before we do that. Many thanks to everyone involved in testing and figuring out these various solutions 👍

**Comment by Voyz** [comment]
Closing this as [`v0.4.0`][v040] just got released which should fix this issue. Feel free to open a new issue if you'd like to continue the discussion 👍 Thank you for participating!

[v040]: https://github.com/Voyz/ibeam/releases/tag/v0.4.0
